#TOML v0.5.0

modLoader="javafml"
loaderVersion="[26,)"
issueTrackerURL="https://github.com/UpcraftLP/RandomLootCrates/issues"

[[mods]]
    modId="random_loot_crates"
    version="${file.jarVersion}"
    displayName="Random Loot Crates"
    #updateJSONURL=
    #logoFile="assets/random_loot_crates/icon.png"
    displayURL="https://minecraft.curseforge.com/projects/324370" #optional
    authors="UpcraftLP"
    description='''
    Use any item as loot bag or to place a lootbox.
    '''
[[dependencies.random_loot_crates]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.2,1.15)"
    ordering="NONE"
    side="BOTH"